/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.pro.aluno.processodeproducao.view;

import br.pro.aluno.processodeproducao.model.FuncionarioModel;
import jasperreporttest.RelCliente;
import java.net.URL;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Casa
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jmiPrincipal = new javax.swing.JMenuBar();
        jmiCadastros = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiFuncionario = new javax.swing.JMenuItem();
        jmiProduto = new javax.swing.JMenuItem();
        jmiPeca = new javax.swing.JMenuItem();
        jmiMtPrima = new javax.swing.JMenuItem();
        jmiMontagem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSair = new javax.swing.JMenuItem();
        jPedido = new javax.swing.JMenu();
        jmiDadosPedidos = new javax.swing.JMenuItem();
        jmiFazerPedido = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiControPeca = new javax.swing.JMenuItem();
        jmRelatorio = new javax.swing.JMenu();
        jmirelCli = new javax.swing.JMenuItem();
        jmirelProd = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpPrincipal.setMinimumSize(new java.awt.Dimension(106, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/aluno/gestaoIndustriaInsumos/imagens/image12.png"))); // NOI18N

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1545, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdpPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jmiCadastros.setText("Cadastros");

        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiCliente);

        jmiFuncionario.setText("Funcionario");
        jmiFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFuncionarioActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiFuncionario);

        jmiProduto.setText("Produto");
        jmiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutoActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiProduto);

        jmiPeca.setText("Peça");
        jmiPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPecaActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiPeca);

        jmiMtPrima.setText("Insumo");
        jmiMtPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMtPrimaActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiMtPrima);

        jmiMontagem.setText("Montagem");
        jmiMontagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMontagemActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiMontagem);
        jmiCadastros.add(jSeparator1);

        jmiSair.setText("Sair");
        jmiCadastros.add(jmiSair);

        jmiPrincipal.add(jmiCadastros);

        jPedido.setText("Pedido");

        jmiDadosPedidos.setText("Dados do Pedidos");
        jmiDadosPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDadosPedidosActionPerformed(evt);
            }
        });
        jPedido.add(jmiDadosPedidos);

        jmiFazerPedido.setText("Fazer Pedido");
        jmiFazerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFazerPedidoActionPerformed(evt);
            }
        });
        jPedido.add(jmiFazerPedido);

        jmiPrincipal.add(jPedido);

        jMenu1.setText("Controle");

        jmiControPeca.setText("Controle Peça");
        jmiControPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiControPecaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiControPeca);

        jmiPrincipal.add(jMenu1);

        jmRelatorio.setText("Relatorios");

        jmirelCli.setText("Relatório de Clientes");
        jmirelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmirelCliActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmirelCli);

        jmirelProd.setText("Relatório de Produtos");
        jmirelProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmirelProdActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmirelProd);

        jmiPrincipal.add(jmRelatorio);

        jMenu2.setText("Edit");
        jmiPrincipal.add(jMenu2);

        setJMenuBar(jmiPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutoActionPerformed
    JIFProduto janela = new JIFProduto();
    jdpPrincipal.add(janela);
    janela.setVisible(true);
    }//GEN-LAST:event_jmiProdutoActionPerformed

    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
     JIFCliente janela = new JIFCliente();
     jdpPrincipal.add(janela);
     janela.setVisible(true);
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmiFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFuncionarioActionPerformed
      JIFFuncionario janela = new JIFFuncionario();
      jdpPrincipal.add(janela);
      janela.setVisible(true);
    }//GEN-LAST:event_jmiFuncionarioActionPerformed

    private void jmiFazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFazerPedidoActionPerformed
       JIFPedidoProduto janela = new JIFPedidoProduto();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiFazerPedidoActionPerformed

    private void jmiDadosPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDadosPedidosActionPerformed
        JIFPedidos janela = new JIFPedidos();
         jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiDadosPedidosActionPerformed

    private void jmiPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPecaActionPerformed
        JIFPeca janela = new JIFPeca();
         jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiPecaActionPerformed

    private void jmiMtPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMtPrimaActionPerformed
        JIFMatPrima janela = new JIFMatPrima();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiMtPrimaActionPerformed

    private void jmiControPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiControPecaActionPerformed
       JIFControPeca janela = new JIFControPeca();
       jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiControPecaActionPerformed

    private void jmiMontagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMontagemActionPerformed
       JIFProdutoPeca janela = new JIFProdutoPeca();
       jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiMontagemActionPerformed

    private void jmirelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmirelCliActionPerformed
        try {
            //Cria uma instância desta classe para poder usar o método getClass()
            //Em métodos de JFrames, por exemplo, no lugar de jrt pode-se...
            //...empregar o comando "this" (this.getClass().getResource(...)).
            RelCliente jrt = new RelCliente();
            //O método getResource(...) procura por um recurso (arquivo)...
            //..a partir do diretório onde está a classe retornando sua URL.
            URL url = jrt.getClass().getResource("./reports/relCliente.jrxml");
            //A URL do recurso precisa ser convertida para path de arquivo.
            //String path = Paths.of(url.toURI()).toString();
            String path = Paths.get(url.toURI()).toString();
            System.out.println("Path para o JRXML: "+path);
            //Conexão com banco de dados - Mesma configuração usada para...
            //...conectar a origem dos dados no Repository Explorer do...
            //...Jaspersoft Studio.
            Connection con = null;
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/bdprocessodeproducao","postgres","lara2011");
            //Compila o relatório conforme o arquivo JRXML presente no path.
            JasperReport jr = JasperCompileManager.compileReport(path);
            //Preenche o relatório com dados conforme a consulta SQL presente...
            //...no JRXML e a conexão com BD estabelecida.
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            //Executa o visualizador de relatórios do Jasper (JasperViewer).
            JasperViewer.viewReport(jp);
            //Fecha a conexão com BD.
            con.close();
        } catch(Exception ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_jmirelCliActionPerformed

    private void jmirelProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmirelProdActionPerformed
        try {
            //Cria uma instância desta classe para poder usar o método getClass()
            //Em métodos de JFrames, por exemplo, no lugar de jrt pode-se...
            //...empregar o comando "this" (this.getClass().getResource(...)).
            RelCliente jrt = new RelCliente();
            //O método getResource(...) procura por um recurso (arquivo)...
            //..a partir do diretório onde está a classe retornando sua URL.
            URL url = jrt.getClass().getResource("./reports/relProduto.jrxml");
            //A URL do recurso precisa ser convertida para path de arquivo.
            //String path = Paths.of(url.toURI()).toString();
            String path = Paths.get(url.toURI()).toString();
            System.out.println("Path para o JRXML: "+path);
            //Conexão com banco de dados - Mesma configuração usada para...
            //...conectar a origem dos dados no Repository Explorer do...
            //...Jaspersoft Studio.
            Connection con = null;
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/bdprocessodeproducao","postgres","lara2011");
            //Compila o relatório conforme o arquivo JRXML presente no path.
            JasperReport jr = JasperCompileManager.compileReport(path);
            //Preenche o relatório com dados conforme a consulta SQL presente...
            //...no JRXML e a conexão com BD estabelecida.
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            //Executa o visualizador de relatórios do Jasper (JasperViewer).
            JasperViewer.viewReport(jp);
            //Fecha a conexão com BD.
            con.close();
        } catch(Exception ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_jmirelProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jPedido;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu jmRelatorio;
    private javax.swing.JMenu jmiCadastros;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiControPeca;
    private javax.swing.JMenuItem jmiDadosPedidos;
    private javax.swing.JMenuItem jmiFazerPedido;
    private javax.swing.JMenuItem jmiFuncionario;
    private javax.swing.JMenuItem jmiMontagem;
    private javax.swing.JMenuItem jmiMtPrima;
    private javax.swing.JMenuItem jmiPeca;
    private javax.swing.JMenuBar jmiPrincipal;
    private javax.swing.JMenuItem jmiProduto;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmirelCli;
    private javax.swing.JMenuItem jmirelProd;
    // End of variables declaration//GEN-END:variables
}
